name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps --force

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Verify AWS Credentials
      run: aws sts get-caller-identity

    - name: Download Chromium
      run: |
        echo "Attempting to download Chromium from S3..."
        aws s3 cp s3://chromium-binary-db/chromium.zip chromium.zip --region ap-south-1
        echo "Download complete."
        mkdir -p chromium
        unzip chromium.zip -d chromium
        rm chromium.zip

    - name: Create ZIP file
      run: |
        zip -r function.zip . -x "*.git*" -x "*.log" -x ".lambdaignore" -x "node_modules/.bin/*"

    - name: Upload to S3
      run: |
        echo "Uploading function.zip to S3..."
        aws s3 cp function.zip s3://pdf-code-db/function.zip --region ap-south-1
        echo "Upload complete."

    - name: Update Lambda Function
      run: |
        echo "Updating Lambda function..."
        aws lambda update-function-code \
          --function-name pdf-generator \
          --s3-bucket pdf-code-db \
          --s3-key function.zip \
          --region ap-south-1
        echo "Lambda function update complete."
